version: '3'

services:
  backend:
    build:
      context: ./server
    volumes:
      - ./server:/var/server
    depends_on:
      - app_db
    networks:
      - diekeditora

  frontend:
    build:
      context: ./web
    volumes:
      - ./web:/var/www
    ports:
      - ${PORT:-3000}:3000
    networks:
      - diekeditora

  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ 'redis-server', '/redis.conf' ]
    networks:
      - diekeditora

networks:
  diekeditora:
    driver: bridge

volumes:
  postgres:
    driver: local
