version: '3'

services:
  backend:
    build:
      context: ./server
    volumes:
      - ./server:/var/server
    depends_on:
      - app_db
    networks:
      - diekeditora

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/var/www
    env_file:
      - frontend/.env
    ports:
      - ${PORT:-3000}:3000
    networks:
      - diekeditora

  app_db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres:/var/lib/postgres
    networks:
      - diekeditora

networks:
  diekeditora:
    driver: bridge

volumes:
  postgres:
    driver: local
