version: '3'

services:
  server:
    image : registry.digitalocean.com/diekeditora/server:latest
    volumes:
      - ./server:/var/server
      - ./.credentials/firebase.json:/firebase.json
    env_file:
      - ./server/.env
    depends_on:
      - database
    networks:
      - diekeditora

  database:
    image: postgres:13.2
    restart: always
    env_file:
      - ./dev/database/.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - diekeditora

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./dev/config/redis.conf:/redis.conf
    command: [ 'redis-server', '/redis.conf' ]
    networks:
      - diekeditora

networks:
  diekeditora:
    driver: bridge

volumes:
  postgres:
    driver: local
