import React from 'react';

import Head from 'next/head';
import Image from 'next/image';

import api from '~/api';
import { firebase } from '~/config';

import styles from '~/styles/Home.module.scss';

export default function Home() {
  const handleLogin = () => {
    firebase
      .auth()
      .signInWithPopup(new firebase.auth.GoogleAuthProvider())
      .then(async (data) => {
        if (!data.user) {
          return;
        }

        const token = await data.user.getIdToken();
        const session = await api.get('/session', {
          headers: {
            Authorization: 'Bearer ' + token,
          },
        });

        console.log('session', session.data);
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Diek Editora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://diekeditora.com">DiekEditora!</a>
        </h1>

        <div className={styles.grid}>
          <button className={styles.card} onClick={handleLogin}>
            <h2>Login &rarr;</h2>
            <p>
              Log-in into your account by social providers like google,
              facebook, twitter, etc
            </p>
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
