apiVersion: v1
kind: Pod
metadata:
  name: redis

spec:
  containers:
    - name: cache
      image: redis:alpine
      command:
        - redis-server
        - /redis-master/redis.conf

      env:
        - name: MASTER
          value: 'true'

      ports:
        - containerPort: 6379

      resources:
        limits:
          cpu: '0.1'

      volumeMounts:
        - mountPath: /redis-master-data
          name: data

        - mountPath: /redis-master
          name: config

  volumes:
    - name: data
      emptyDir: { }

    - name: config
      configMap:
        name: diekeditora-redis-config
        items:
          - key: redis-conf
            path: 'redis.conf'
