server:
  port: ${PORT:8080}

  error:
    whitelabel:
      enabled: false

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    name: ${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security.oauth2.client:
    registration:
      google:
        client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
        client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
        redirect-uri: ${OAUTH2_REDIRECT_URI}

      github:
        client-id: ${GITHUB_OAUTH2_CLIENT_ID}
        client-secret: ${GITHUB_OAUTH2_CLIENT_SECRET}
        redirect-uri: ${OAUTH2_REDIRECT_URI}

      facebook:
        client-id: ${FACEBOOK_OAUTH2_CLIENT_ID}
        client-secret: ${FACEBOOK_OAUTH2_CLIENT_SECRET}
        redirect-uri: ${OAUTH2_REDIRECT_URI}

logging:
  level:
    root: ${LOG_LEVEL:info}
    org.springframework.web:
      - error
      - warn
      - info
    com.expediagroup.graphql.server.spring.NonFederatedSchemaAutoConfiguration: error
    com.expediagroup.graphql: error
    notprivacysafe.graphql.GraphQL: error

graphql:
  packages:
    - com.lorenzoog.diekeditora.domain
    - com.lorenzoog.diekeditora.web
    - graphql.relay
